version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: catalisa
      POSTGRES_DB: catalisa_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: catalisa
      POSTGRES_DB: catalisa_db_test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
